<?php 
const ROUTES = [
    "06-poo"=>[
        "controller"=>"UserController",
        "fonction"=>"read"
    ],
    "06-poo/inscription"=>[
        "controller"=>"UserController",
        "fonction"=>"create"
    ],
    "06-poo/user/update"=>[
        "controller"=>"UserController",
        "fonction"=>"update"
    ],
    "06-poo/user/delete"=>[
        "controller"=>"UserController",
        "fonction"=>"delete"
    ],
    // Exercices :
    "06-poo/connexion"=>[
        "controller"=>"AuthController",
        "fonction"=>"login"
    ],
    "06-poo/deconnexion"=>[
        "controller"=>"AuthController",
        "fonction"=>"logout"
    ],
    "06-poo/message/list"=>[
        "controller"=>"MessageController",
        "fonction"=>"read"
    ],
    "06-poo/message/create"=>[
        "controller"=>"MessageController",
        "fonction"=>"create"
    ],
    "06-poo/message/update"=>[
        "controller"=>"MessageController",
        "fonction"=>"update"
    ],
    "06-poo/message/delete"=>[
        "controller"=>"MessageController",
        "fonction"=>"delete"
    ],
];
?>